### ISSUE TITLE
Cannot find module '@babel-core' error

### ISSUE THREAD

**Issue by jawittdesigns** [babel/gulp-babel#150]
I'm getting the error on the latest version

`Error: Cannot find module '@babel-core'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path-to/index.js:7:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)`

If I revert the `babel` const in index.js from `@babel/core` back to `babel-core` it seems to  work again.

**Comment by motss** [comment]
@jawittdesigns @hzoo 

Encountered this issue as well. Package author should tag the release if it is not meant for stable such as tagging any beta version as `next`. Read [npm publish with tags](https://docs.npmjs.com/getting-started/using-tags) with more details.

Users might encounter dependency conflict as the latest beta version will be treated as lastest version unlike the tagged version where users need to do the following in order to use the latest and the greatest:

```sh
$ npm i -D gulp-babel # Install latest stable version, `gulp-babel@7.0.1`
$ npm i -D gulp-babel@next # Install latest beta version, `gulp-babel@8.0.0-beta.2
```

**Comment by hzoo** [comment]
`@babel-core` is not a package? It should be `@babel/core`.

And yes 8.0.0-beta should be on `next`, I'll change it

**Comment by hu-qi** [comment]
感谢 遇到同样的问题  我这边默认安装的版本是next 8.0.0 而babel-core默认装的6.26.3 导致不匹配，gulp-babel@^8.0.0要求babel-core^7.0.0。
解决方法：安装匹配的gulp-babel 和babel-core

![image](https://user-images.githubusercontent.com/17986122/46203400-3e99d580-c34c-11e8-8c64-ab33b175b134.png)
