### ISSUE TITLE
Error when running from script $npm run build with local gulp

### ISSUE THREAD

**Issue by PrimeLens** [babel/gulp-babel#73]
I've put together the minimum amount of code to demonstrate this error at this repo 

https://github.com/PrimeLens/gulp-babel-issue/blob/master/README.md

**Comment by PrimeLens** [comment]
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "gulp build"
  },

$npm run build

npm ERR! server@0.0.1 build: gulp build
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the server@0.0.1 build script.
npm ERR! This is most likely a problem with the server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! gulp build
npm ERR! You can get their info via:
npm ERR! npm owner ls server
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "build"
npm ERR! cwd /Users/.../gulp-babel-issue
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! /Users/.../gulp-babel-issue/npm-debug.log
npm ERR! not ok code 0

**Comment by sindresorhus** [comment]
Support => https://github.com/babel/babel#looking-for-support

**Comment by PrimeLens** [comment]
Just want to point out that npm run <script> works fine with concat, inject and a whole host of other gulp modules. It fails with gulp-babel.

**Comment by loganfsmyth** [comment]
@PrimeLens If you run that gulp script, at least for me it prints a very clear parse error for JSX. Your issue is not with gulp-babel, it is with Babel's configuration itself. gulp-babel is a simple wrapper on Babel, which is managed in an entirely separate repository with different support channels.

You are missing the `react` preset so parsing JSX will error out.

**Comment by PrimeLens** [comment]
@loganfsmyth Hi Logan and thanks for responding. I've used grunt-babel with much success and its implementation was dead simple. There was no extra react preset.  I'm following the readme in gulp-babel and it does not mention a react preset either. Where is this react preset? Why is it needed and why would't it be mentioned in the readme for gulp-babel?

**Comment by loganfsmyth** [comment]
@PrimeLens `gulp-babel` is a simple is a wrapper and its README is about how to use trigger Babel via Gulp, it is _not_ about how to use Babel itself. Babel has a whole website section devoted to how to set it up: http://babeljs.io/docs/setup/ and http://babeljs.io/docs/plugins/

I would expect grunt-babel to fail in the same way. As mentioned above, Babel's support channels are documented in https://github.com/babel/babel#looking-for-support, if you have specific questions, that is the recommended approach.

**Comment by PrimeLens** [comment]
@loganfsmyth I looked back at my old uses of grunt-babel and they were with babel v5.  This babel 6 is very frustrating, so far I've added   `"babel": { "plugins": ["transform-react-jsx"] }` to package.json as well as `{ "presets": ["es2015"] }` to .babelrc as well as `npm install --save-dev babel-preset-es2015`  and I'm still getting the same error. Any advice? I'm even considering looking for an older version of gulp-babel that uses v5

**Comment by loganfsmyth** [comment]
@PrimeLens Don't split up your config, in two places. You just need `{"presets": ["es2015", "react"]}` and `npm install --save-dev babel-preset-react babel-preset-es2015`

**Comment by PrimeLens** [comment]
@loganfsmyth once again thanks for sticking around and helping me through this.  Your last comment had a *massive" clue because your npm install command contained *two* modules not one like in the docs at https://babeljs.io/docs/setup/#gulp

**Comment by loganfsmyth** [comment]
In this particular case, both are optional, in your case, you want two because you are using JSX, so you need to tell Babel to parse and convert React, and you generally want `es2015` because without it, Babel would just pass through ES6 code unchanged. The docs on the page you linked to for instance call out

> Pre-6.x, Babel enabled certain transformations by default. However, Babel 6.x does not ship with any transformations enabled. You need to explicitly tell it what transformations to run. The simplest way to do this is by using a preset, such as the ES2015 Preset. You can install it with

>> npm install babel-preset-es2015 --save-dev

The docs are meant as a starting point, not the be-all and end all of directions.

Thank you for the feedback though. Docs are tough and definitely something we're still iterating on. If you have specific suggestions, feel free to let us know, though in this case I don't know we'd want the docs to instruct people to install two presets, perhaps there are ways we can make the configurability clearer.

**Comment by PrimeLens** [comment]
I've renamed the original repo so its now a working example   
https://github.com/PrimeLens/working-example-gulp-babel-with-babel6-JSX

Thanks Logan!
