### ISSUE TITLE
Error message with direct.presets

### ISSUE THREAD

**Issue by DominicBoettger** [babel/gulp-babel#79]
The code is compiling but it get these errors:

20:56:33] Plumber found unhandled error:
 ReferenceError in plugin 'gulp-babel'
Message:
    [BABEL] /src/app/alert/alert.tpl.js: Unknown option: direct.presets
[20:56:33] Finished 'sass' after 3.91 s

My gulp config:

``` js
import babel from 'gulp-babel';

var babelCompilerOptions = {
    presets: ['es2015'],
    plugins: ['transform-es2015-modules-systemjs']
};

gulp.task('js:compile', () => {
    return gulp.src(path.source)
        .pipe(babel(babelCompilerOptions))
        .pipe(gulp.dest(path.output));
});
```

**Comment by michaelBenin** [comment]
@DominicBoettger this can be caused by a few things:

- Check to see if you are on the latest gulp-babel
- Make sure all the transforms / plugins you are using are installed
- Check in your home directory for a .babelrc or a .babel.json 
- Check your globally installed version of babel
- Run a find . '.babelrc' to see if there's any other configs around from babel 5

I ran into the same issue today. Turns out this older project had an old version of gulp-babel installed. 

Good luck.

**Comment by michaelBenin** [comment]
Related: https://github.com/babel/babel-loader/issues/132

**Comment by cvibhagool** [comment]
I'm having the same issue here.

- I'm on the latest gulp-babel using npm install
- all my plugins are installed
- no .babelrc or .babel.json anywhere
- no globally installed babel
- I only found bookshelf.js within node_modules using .babelrc

I also tried doing `presets: []`, and I got the same error.
@DominicBoettger Anywhere else I should look? Cheers

**Comment by loganfsmyth** [comment]
If you're still having issues, I'd recommend dropping by our support channel on Slack: https://github.com/babel/babel#looking-for-support

**Comment by michaelBenin** [comment]
@cvibhagool what version do you have installed?

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
