### ISSUE TITLE
gulp-babel + nyc gives wrong paths in coverage reports

### ISSUE THREAD

**Issue by chiel** [babel/gulp-babel#94]
Hi, I've also made an issue over at https://github.com/istanbuljs/nyc/issues/359, but this is starting to look more like a `gulp-babel` issue than an nyc issue.

I would really appreciate if someone here could have a look!

**Comment by demurgos** [comment]
@chiel
I remember having similar issues with `nyc`, mine was caused by gulp and Typescript.

I see that the original issue you linked is closed. Is it fixed or do we need to update something here?

**Comment by loganfsmyth** [comment]
I'm triaging old issues on gulp-babel. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

If someone runs across this, feel free to file a new issue with a reproduction repository.
